/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewRouteImport } from './routes/new'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WriteIdRouteImport } from './routes/write.$id'
import { Route as ReadIdRouteImport } from './routes/read.$id'
import { Route as PublishIdRouteImport } from './routes/publish.$id'
import { Route as CoverIdRouteImport } from './routes/cover.$id'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteIdRoute = WriteIdRouteImport.update({
  id: '/write/$id',
  path: '/write/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIdRoute = ReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishIdRoute = PublishIdRouteImport.update({
  id: '/publish/$id',
  path: '/publish/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverIdRoute = CoverIdRouteImport.update({
  id: '/cover/$id',
  path: '/cover/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contests': typeof ContestsRoute
  '/discover': typeof DiscoverRoute
  '/goals': typeof GoalsRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/upgrade': typeof UpgradeRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/cover/$id': typeof CoverIdRoute
  '/publish/$id': typeof PublishIdRoute
  '/read/$id': typeof ReadIdRoute
  '/write/$id': typeof WriteIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contests': typeof ContestsRoute
  '/discover': typeof DiscoverRoute
  '/goals': typeof GoalsRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/upgrade': typeof UpgradeRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/cover/$id': typeof CoverIdRoute
  '/publish/$id': typeof PublishIdRoute
  '/read/$id': typeof ReadIdRoute
  '/write/$id': typeof WriteIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contests': typeof ContestsRoute
  '/discover': typeof DiscoverRoute
  '/goals': typeof GoalsRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/upgrade': typeof UpgradeRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/cover/$id': typeof CoverIdRoute
  '/publish/$id': typeof PublishIdRoute
  '/read/$id': typeof ReadIdRoute
  '/write/$id': typeof WriteIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contests'
    | '/discover'
    | '/goals'
    | '/new'
    | '/profile'
    | '/upgrade'
    | '/checkout/success'
    | '/cover/$id'
    | '/publish/$id'
    | '/read/$id'
    | '/write/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contests'
    | '/discover'
    | '/goals'
    | '/new'
    | '/profile'
    | '/upgrade'
    | '/checkout/success'
    | '/cover/$id'
    | '/publish/$id'
    | '/read/$id'
    | '/write/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contests'
    | '/discover'
    | '/goals'
    | '/new'
    | '/profile'
    | '/upgrade'
    | '/checkout/success'
    | '/cover/$id'
    | '/publish/$id'
    | '/read/$id'
    | '/write/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContestsRoute: typeof ContestsRoute
  DiscoverRoute: typeof DiscoverRoute
  GoalsRoute: typeof GoalsRoute
  NewRoute: typeof NewRoute
  ProfileRoute: typeof ProfileRoute
  UpgradeRoute: typeof UpgradeRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CoverIdRoute: typeof CoverIdRoute
  PublishIdRoute: typeof PublishIdRoute
  ReadIdRoute: typeof ReadIdRoute
  WriteIdRoute: typeof WriteIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/$id': {
      id: '/write/$id'
      path: '/write/$id'
      fullPath: '/write/$id'
      preLoaderRoute: typeof WriteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish/$id': {
      id: '/publish/$id'
      path: '/publish/$id'
      fullPath: '/publish/$id'
      preLoaderRoute: typeof PublishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover/$id': {
      id: '/cover/$id'
      path: '/cover/$id'
      fullPath: '/cover/$id'
      preLoaderRoute: typeof CoverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContestsRoute: ContestsRoute,
  DiscoverRoute: DiscoverRoute,
  GoalsRoute: GoalsRoute,
  NewRoute: NewRoute,
  ProfileRoute: ProfileRoute,
  UpgradeRoute: UpgradeRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CoverIdRoute: CoverIdRoute,
  PublishIdRoute: PublishIdRoute,
  ReadIdRoute: ReadIdRoute,
  WriteIdRoute: WriteIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
