/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NewRouteImport } from './routes/new'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WriteIdRouteImport } from './routes/write.$id'
import { Route as UPenNameRouteImport } from './routes/u.$penName'
import { Route as ReadIdRouteImport } from './routes/read.$id'
import { Route as PublishIdRouteImport } from './routes/publish.$id'
import { Route as EmbedIdRouteImport } from './routes/embed.$id'
import { Route as CoverIdRouteImport } from './routes/cover.$id'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteIdRoute = WriteIdRouteImport.update({
  id: '/write/$id',
  path: '/write/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UPenNameRoute = UPenNameRouteImport.update({
  id: '/u/$penName',
  path: '/u/$penName',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIdRoute = ReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishIdRoute = PublishIdRouteImport.update({
  id: '/publish/$id',
  path: '/publish/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedIdRoute = EmbedIdRouteImport.update({
  id: '/embed/$id',
  path: '/embed/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverIdRoute = CoverIdRouteImport.update({
  id: '/cover/$id',
  path: '/cover/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contests': typeof ContestsRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/goals': typeof GoalsRoute
  '/invite': typeof InviteRoute
  '/manage': typeof ManageRoute
  '/marketing': typeof MarketingRoute
  '/new': typeof NewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/book/$slug': typeof BookSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/cover/$id': typeof CoverIdRoute
  '/embed/$id': typeof EmbedIdRoute
  '/publish/$id': typeof PublishIdRoute
  '/read/$id': typeof ReadIdRoute
  '/u/$penName': typeof UPenNameRoute
  '/write/$id': typeof WriteIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contests': typeof ContestsRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/goals': typeof GoalsRoute
  '/invite': typeof InviteRoute
  '/manage': typeof ManageRoute
  '/marketing': typeof MarketingRoute
  '/new': typeof NewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/book/$slug': typeof BookSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/cover/$id': typeof CoverIdRoute
  '/embed/$id': typeof EmbedIdRoute
  '/publish/$id': typeof PublishIdRoute
  '/read/$id': typeof ReadIdRoute
  '/u/$penName': typeof UPenNameRoute
  '/write/$id': typeof WriteIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contests': typeof ContestsRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/goals': typeof GoalsRoute
  '/invite': typeof InviteRoute
  '/manage': typeof ManageRoute
  '/marketing': typeof MarketingRoute
  '/new': typeof NewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/book/$slug': typeof BookSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/cover/$id': typeof CoverIdRoute
  '/embed/$id': typeof EmbedIdRoute
  '/publish/$id': typeof PublishIdRoute
  '/read/$id': typeof ReadIdRoute
  '/u/$penName': typeof UPenNameRoute
  '/write/$id': typeof WriteIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/bookmarks'
    | '/contests'
    | '/discover'
    | '/feed'
    | '/goals'
    | '/invite'
    | '/manage'
    | '/marketing'
    | '/new'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/upgrade'
    | '/book/$slug'
    | '/checkout/success'
    | '/cover/$id'
    | '/embed/$id'
    | '/publish/$id'
    | '/read/$id'
    | '/u/$penName'
    | '/write/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/bookmarks'
    | '/contests'
    | '/discover'
    | '/feed'
    | '/goals'
    | '/invite'
    | '/manage'
    | '/marketing'
    | '/new'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/upgrade'
    | '/book/$slug'
    | '/checkout/success'
    | '/cover/$id'
    | '/embed/$id'
    | '/publish/$id'
    | '/read/$id'
    | '/u/$penName'
    | '/write/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/bookmarks'
    | '/contests'
    | '/discover'
    | '/feed'
    | '/goals'
    | '/invite'
    | '/manage'
    | '/marketing'
    | '/new'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/upgrade'
    | '/book/$slug'
    | '/checkout/success'
    | '/cover/$id'
    | '/embed/$id'
    | '/publish/$id'
    | '/read/$id'
    | '/u/$penName'
    | '/write/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  ContestsRoute: typeof ContestsRoute
  DiscoverRoute: typeof DiscoverRoute
  FeedRoute: typeof FeedRoute
  GoalsRoute: typeof GoalsRoute
  InviteRoute: typeof InviteRoute
  ManageRoute: typeof ManageRoute
  MarketingRoute: typeof MarketingRoute
  NewRoute: typeof NewRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UpgradeRoute: typeof UpgradeRoute
  BookSlugRoute: typeof BookSlugRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CoverIdRoute: typeof CoverIdRoute
  EmbedIdRoute: typeof EmbedIdRoute
  PublishIdRoute: typeof PublishIdRoute
  ReadIdRoute: typeof ReadIdRoute
  UPenNameRoute: typeof UPenNameRoute
  WriteIdRoute: typeof WriteIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/$id': {
      id: '/write/$id'
      path: '/write/$id'
      fullPath: '/write/$id'
      preLoaderRoute: typeof WriteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$penName': {
      id: '/u/$penName'
      path: '/u/$penName'
      fullPath: '/u/$penName'
      preLoaderRoute: typeof UPenNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish/$id': {
      id: '/publish/$id'
      path: '/publish/$id'
      fullPath: '/publish/$id'
      preLoaderRoute: typeof PublishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$id': {
      id: '/embed/$id'
      path: '/embed/$id'
      fullPath: '/embed/$id'
      preLoaderRoute: typeof EmbedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover/$id': {
      id: '/cover/$id'
      path: '/cover/$id'
      fullPath: '/cover/$id'
      preLoaderRoute: typeof CoverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  ContestsRoute: ContestsRoute,
  DiscoverRoute: DiscoverRoute,
  FeedRoute: FeedRoute,
  GoalsRoute: GoalsRoute,
  InviteRoute: InviteRoute,
  ManageRoute: ManageRoute,
  MarketingRoute: MarketingRoute,
  NewRoute: NewRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UpgradeRoute: UpgradeRoute,
  BookSlugRoute: BookSlugRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CoverIdRoute: CoverIdRoute,
  EmbedIdRoute: EmbedIdRoute,
  PublishIdRoute: PublishIdRoute,
  ReadIdRoute: ReadIdRoute,
  UPenNameRoute: UPenNameRoute,
  WriteIdRoute: WriteIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
